cc_library(
    name = 'encoding',
    srcs = 'charset_converter.cc'
)

#cc_test(
#    name = 'charset_converter_test',
#    srcs = 'charset_converter_test.cpp',
#    deps = [
#        ':encoding'
#    ]
#)
