
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE  gunir_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE  gunir_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via  gunir_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void  gunir_restart (FILE *input_file ,yyscan_t yyscanner );
void  gunir__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE  gunir__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void  gunir__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void  gunir__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void  gunir_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void  gunir_pop_buffer_state (yyscan_t yyscanner );

static void  gunir_ensure_buffer_stack (yyscan_t yyscanner );
static void  gunir__load_buffer_state (yyscan_t yyscanner );
static void  gunir__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER  gunir__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE  gunir__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE  gunir__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE  gunir__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void * gunir_alloc (yy_size_t ,yyscan_t yyscanner );
void * gunir_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void  gunir_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer  gunir__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
         gunir_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
             gunir__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
         gunir_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
             gunir__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[202] =
    {   0,
        0,    0,    0,    0,   85,   83,   82,   82,   17,   69,
       22,    9,   70,   27,   28,   19,   20,   25,   21,   23,
       18,   67,   24,   26,    2,    6,    4,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   29,   30,   12,   31,   11,
       32,   10,   81,   72,   71,   80,   82,    8,   15,    0,
       67,   13,    1,    7,    5,    3,   14,   66,   66,   66,
       44,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   51,   59,
       66,   66,   66,   66,   66,   66,   66,   66,   16,   81,

       75,   74,   76,   77,   78,   79,   73,   68,   60,   57,
       66,   66,   66,   66,   66,   63,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   61,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   76,   66,
       66,   66,   56,   66,   40,   37,   66,   45,   66,   66,
       35,   66,   66,   47,   49,   66,   66,   66,   36,   66,
       66,   34,   64,   66,   66,   76,   66,   66,   66,   66,
       65,   66,   66,   66,   48,   58,   66,   50,   66,   66,
       46,   66,   66,   39,   38,   66,   66,   53,   66,   66,
       43,   41,   42,   66,   66,   52,   33,   54,   62,   55,

        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   34,
       49,   50,   51,   52,   34,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   62,   34,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
       76,   34,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    2,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[205] =
    {   0,
        0,    0,   78,   79,  131,  778,   86,   88,   98,  778,
      778,  107,  778,  778,  778,  778,  778,  778,  778,  778,
      778,   77,  778,  778,   75,   83,   77,   84,   86,   89,
       91,   93,   98,   95,  129,  100,  107,  152,  125,  157,
      159,  161,  179,  154,  188,  778,  778,  778,  778,   15,
      778,  778,    0,  778,  778,  207,  131,  778,  778,  170,
      199,  778,  778,  778,  778,  778,  778,  175,  182,  210,
      215,  217,  228,  234,  241,  243,  247,  256,  250,  272,
      276,  278,  280,  283,  285,  289,  306,  308,  225,  310,
      312,  326,  314,  317,  336,  342,  339,  345,  778,    0,

      778,  778,  347,  354,  778,  778,  778,  358,  360,  364,
      367,  373,  375,  377,  381,  383,  388,  391,  395,  403,
      400,  413,  411,  405,  423,  429,  425,  439,  436,  441,
      464,  443,  446,  471,  473,  485,  488,  491,  493,  499,
      507,  509,  513,  516,  518,  520,  526,  522,  541,  538,
      543,  546,  548,  550,  552,  554,  564,  568,  570,  573,
      575,  577,  581,  593,  602,  589,  606,  598,  611,  614,
      618,  623,  626,  628,  635,  640,  647,  642,  644,  656,
      658,  665,  669,  663,  671,  677,  673,  675,  687,  690,
      692,  694,  696,  698,  700,  702,  705,  707,  711,  719,

      778,  771,   82,  774
    } ;

static yyconst flex_int16_t yy_def[205] =
    {   0,
      201,    1,  202,  202,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  201,  201,  201,  201,  201,
      201,  201,  204,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  201,  204,

      201,  201,  201,  201,  201,  201,  201,  201,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  201,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  201,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

        0,  201,  201,  201
    } ;

static yyconst flex_int16_t yy_nxt[859] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   29,   38,   29,   39,   40,   29,   41,
       42,   43,   44,   29,   29,   45,   29,   29,   46,    6,
       47,   48,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   29,   39,   40,   29,   41,   42,   43,
       44,   29,   29,   45,   29,   29,   49,   50,   51,   52,
       54,   54,   55,   55,   69,   55,   55,   57,   57,   57,
       57,   60,   99,   61,   61,   62,   63,   64,   66,   67,

       68,   68,   68,   68,   65,   68,   68,   68,   68,   68,
       68,   68,   68,   59,   68,   68,   68,   68,   74,   58,
       70,   78,   75,   68,   68,   71,   72,   56,   56,   73,
      201,   76,   57,   57,  201,   80,   84,  201,   79,   77,
      201,   68,   68,  201,   85,   68,   68,   74,   70,  201,
       78,   75,   81,   71,   72,  201,   82,   73,  201,   76,
       83,  201,   88,   80,   84,  201,   79,   77,   68,   68,
       68,   68,   85,   68,   68,   68,   68,   68,   68,   86,
      201,   81,  201,   87,  201,   82,  108,  108,   93,   83,
       88,   68,   68,   89,   96,   68,   68,   90,   68,   68,

       91,  201,   92,  201,   68,   68,   94,  201,   86,   95,
      201,  101,   87,   60,  102,   61,   61,   93,   97,   98,
      201,   89,   96,  103,  104,   90,   68,   68,   91,  201,
       92,   68,   68,   68,   68,   94,  109,  201,   95,  201,
      110,   68,   68,  105,   68,   68,  201,   97,   98,  106,
       68,   68,  201,  111,  201,  112,  107,   68,   68,   68,
       68,  201,  113,   68,   68,  109,   68,   68,  201,  110,
      201,  105,   68,   68,  201,  114,  201,  106,  118,  201,
      117,  111,  115,  201,  112,  116,  201,  120,   68,   68,
      119,  113,   68,   68,   68,   68,   68,   68,  201,   68,

       68,   68,   68,  114,  201,   68,   68,  118,  117,  121,
      115,  201,  123,  116,  201,  120,  126,  127,  119,  125,
      122,  124,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,  201,   68,   68,  201,  130,  121,  201,  133,
      123,  128,   68,   68,  201,  126,  127,  125,  122,  124,
      129,  134,   68,   68,  131,   68,   68,  132,   68,   68,
      201,   68,   68,  139,  104,  130,  137,  201,  133,  128,
      104,  104,  201,  135,  108,  108,   68,   68,  129,  134,
       68,   68,  131,   68,   68,  136,  132,  138,  201,   68,
       68,   68,   68,   68,   68,  137,  141,   68,   68,   68,

       68,  135,  143,  201,   68,   68,  142,   68,   68,  140,
      201,   68,   68,  136,  201,  138,   68,   68,  201,   68,
       68,   68,   68,  144,  201,  141,  145,   68,   68,   68,
       68,  143,  201,  146,  201,  142,  147,  140,  148,   68,
       68,   68,   68,  149,  150,   68,   68,  152,  201,  151,
      153,  144,   68,   68,  145,   68,   68,   68,   68,   68,
       68,  146,   68,   68,  147,  154,  148,  155,  157,  201,
      156,  149,  201,  150,  201,  152,  201,  151,  201,  153,
       68,   68,  201,  160,  201,  159,  201,   68,   68,   68,
       68,  158,  201,  154,  201,  155,  201,  157,  161,  156,

      201,   68,   68,  201,   68,   68,  201,   68,   68,  166,
      104,  160,  163,  159,  201,   68,   68,  201,  162,  201,
      158,  165,  167,   68,   68,   68,   68,  161,  164,   68,
       68,  201,   68,   68,   68,   68,   68,   68,   68,   68,
      201,  163,   68,   68,  201,  169,  162,  170,  201,  168,
      165,  167,  201,  171,   68,   68,  164,   68,   68,   68,
       68,  201,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,  201,  169,  173,  201,  170,  168,  201,  172,
       68,   68,  171,  174,   68,   68,   68,   68,  175,   68,
       68,   68,   68,   68,   68,  201,  176,   68,   68,  201,

      180,  201,  173,  201,  177,  104,  104,  172,  178,   68,
       68,  174,  201,  179,   68,   68,  175,  201,   68,   68,
      181,  201,   68,   68,  176,  184,  201,   68,   68,  180,
       68,   68,  177,  182,   68,   68,  178,  183,  185,   68,
       68,  179,   68,   68,   68,   68,  201,  187,  201,  181,
      186,   68,   68,  201,  184,  188,   68,   68,   68,   68,
       68,   68,  182,   68,   68,  201,  183,  185,  189,  201,
      191,  190,   68,   68,   68,   68,  187,  201,  186,   68,
       68,   68,   68,  201,  188,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,  201,  189,  201,  192,  191,

      190,  193,  195,   68,   68,  194,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
      196,   68,   68,   68,   68,  201,  192,   68,   68,  193,
      201,  195,  201,  194,  197,   68,   68,  198,  201,  199,
      201,  201,  200,  201,  201,  201,  201,  201,  196,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  197,  201,  201,  198,  201,  199,  201,  201,
      200,   53,   53,   53,  100,  201,  100,    5,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201
    } ;

static yyconst flex_int16_t yy_chk[859] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,  203,    3,    4,    7,    7,    8,
        8,   22,   50,   22,   22,   25,   25,   25,   27,   27,

       28,   28,   29,   29,   26,   30,   30,   31,   31,   32,
       32,   34,   34,   12,   33,   33,   36,   36,   31,    9,
       28,   33,   31,   37,   37,   28,   30,    3,    4,   30,
        5,   31,   57,   57,    0,   34,   36,    0,   33,   32,
        0,   39,   39,    0,   37,   35,   35,   31,   28,    0,
       33,   31,   35,   28,   30,    0,   35,   30,    0,   31,
       35,    0,   39,   34,   36,    0,   33,   32,   38,   38,
       44,   44,   37,   40,   40,   41,   41,   42,   42,   38,
        0,   35,    0,   38,    0,   35,   60,   60,   42,   35,
       39,   68,   68,   40,   44,   43,   43,   40,   69,   69,

       40,    0,   41,    0,   45,   45,   43,    0,   38,   43,
        0,   56,   38,   61,   56,   61,   61,   42,   45,   45,
        0,   40,   44,   56,   56,   40,   70,   70,   40,    0,
       41,   71,   71,   72,   72,   43,   70,    0,   43,    0,
       71,   89,   89,   56,   73,   73,    0,   45,   45,   56,
       74,   74,    0,   72,    0,   73,   56,   75,   75,   76,
       76,    0,   74,   77,   77,   70,   79,   79,    0,   71,
        0,   56,   78,   78,    0,   74,    0,   56,   77,    0,
       76,   72,   75,    0,   73,   75,    0,   79,   80,   80,
       78,   74,   81,   81,   82,   82,   83,   83,    0,   84,

       84,   85,   85,   74,    0,   86,   86,   77,   76,   80,
       75,    0,   82,   75,    0,   79,   85,   86,   78,   84,
       81,   83,   87,   87,   88,   88,   90,   90,   91,   91,
       93,   93,    0,   94,   94,    0,   90,   80,    0,   93,
       82,   87,   92,   92,    0,   85,   86,   84,   81,   83,
       88,   94,   95,   95,   91,   97,   97,   92,   96,   96,
        0,   98,   98,  103,  103,   90,   97,    0,   93,   87,
      104,  104,    0,   95,  108,  108,  109,  109,   88,   94,
      110,  110,   91,  111,  111,   96,   92,   98,    0,  112,
      112,  113,  113,  114,  114,   97,  112,  115,  115,  116,

      116,   95,  114,    0,  117,  117,  113,  118,  118,  111,
        0,  119,  119,   96,    0,   98,  121,  121,    0,  120,
      120,  124,  124,  115,    0,  112,  117,  123,  123,  122,
      122,  114,    0,  118,    0,  113,  119,  111,  120,  125,
      125,  127,  127,  121,  122,  126,  126,  124,    0,  123,
      125,  115,  129,  129,  117,  128,  128,  130,  130,  132,
      132,  118,  133,  133,  119,  126,  120,  127,  130,    0,
      128,  121,    0,  122,    0,  124,    0,  123,    0,  125,
      131,  131,    0,  133,    0,  132,    0,  134,  134,  135,
      135,  131,    0,  126,    0,  127,    0,  130,  134,  128,

        0,  136,  136,    0,  137,  137,    0,  138,  138,  139,
      139,  133,  136,  132,    0,  140,  140,    0,  135,    0,
      131,  138,  140,  141,  141,  142,  142,  134,  137,  143,
      143,    0,  144,  144,  145,  145,  146,  146,  148,  148,
        0,  136,  147,  147,    0,  142,  135,  144,    0,  141,
      138,  140,    0,  147,  150,  150,  137,  149,  149,  151,
      151,    0,  152,  152,  153,  153,  154,  154,  155,  155,
      156,  156,    0,  142,  150,    0,  144,  141,    0,  149,
      157,  157,  147,  152,  158,  158,  159,  159,  153,  160,
      160,  161,  161,  162,  162,    0,  156,  163,  163,    0,

      161,    0,  150,    0,  157,  166,  166,  149,  158,  164,
      164,  152,    0,  160,  168,  168,  153,    0,  165,  165,
      164,    0,  167,  167,  156,  168,    0,  169,  169,  161,
      170,  170,  157,  165,  171,  171,  158,  167,  169,  172,
      172,  160,  173,  173,  174,  174,    0,  172,    0,  164,
      170,  175,  175,    0,  168,  173,  176,  176,  178,  178,
      179,  179,  165,  177,  177,    0,  167,  169,  174,    0,
      179,  177,  180,  180,  181,  181,  172,    0,  170,  184,
      184,  182,  182,    0,  173,  183,  183,  185,  185,  187,
      187,  188,  188,  186,  186,    0,  174,    0,  180,  179,

      177,  182,  186,  189,  189,  183,  190,  190,  191,  191,
      192,  192,  193,  193,  194,  194,  195,  195,  196,  196,
      187,  197,  197,  198,  198,    0,  180,  199,  199,  182,
        0,  186,    0,  183,  189,  200,  200,  190,    0,  194,
        0,    0,  195,    0,    0,    0,    0,    0,  187,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  189,    0,    0,  190,    0,  194,    0,    0,
      195,  202,  202,  202,  204,    0,  204,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "gunir/compiler/parser/big_query.ll"
#line 5 "gunir/compiler/parser/big_query.ll"
// Copyright (C) 2015. The Gunir Authors. All rights reserved.
// Author: An Qin <qinan@baidu.com>
//

#include <cstdlib>
#include <cstring>
#include <iostream>

#include "gunir/compiler/parser/big_query_parser.h"
#include "gunir/compiler/parser/big_query.yy.hh"

#define YY_USER_ACTION \
        gunir_lloc.first_column = yycolumn; \
        gunir_lloc.last_column = yycolumn + yyleng - 1; \
        yycolumn += yyleng;

#define YY_USER_INIT gunir_lloc.first_line = 0; \
                     gunir_lloc.last_line = 0; \
                     gunir_lloc.first_column = 0; \
                     gunir_lloc.last_column = 0

#define YY_DECL int  gunir_lex(yyscan_t yyscanner,YaccMemoryPool* memory_pool,std::ostream* output)
static void print_message(const char* msg, std::ostream* output);

namespace dc = ::gunir::compiler;
static std::string char_string_content;
enum QuoteType {
    kNone = 0,
    kSingle = 1,
    kDouble = 2
};

static QuoteType quote_type = kNone;

#line 753 "<stdout>"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int  gunir_lex_init (yyscan_t* scanner);

int  gunir_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int  gunir_lex_destroy (yyscan_t yyscanner );

int  gunir_get_debug (yyscan_t yyscanner );

void  gunir_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE  gunir_get_extra (yyscan_t yyscanner );

void  gunir_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE * gunir_get_in (yyscan_t yyscanner );

void  gunir_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE * gunir_get_out (yyscan_t yyscanner );

void  gunir_set_out  (FILE * out_str ,yyscan_t yyscanner );

int  gunir_get_leng (yyscan_t yyscanner );

char * gunir_get_text (yyscan_t yyscanner );

int  gunir_get_lineno (yyscan_t yyscanner );

void  gunir_set_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int  gunir_wrap (yyscan_t yyscanner );
#else
extern int  gunir_wrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int  gunir_lex (yyscan_t yyscanner);

#define YY_DECL int  gunir_lex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 44 "gunir/compiler/parser/big_query.ll"

#line 982 "<stdout>"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			 gunir_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				 gunir__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		 gunir__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 202 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 778 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "gunir/compiler/parser/big_query.ll"
{ return LESS_THAN_OR_EQUAL; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "gunir/compiler/parser/big_query.ll"
{ return LESS_THAN; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "gunir/compiler/parser/big_query.ll"
{ return GREATER_THAN_OR_EQUAL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "gunir/compiler/parser/big_query.ll"
{ return GREATER_THAN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "gunir/compiler/parser/big_query.ll"
{ return EQUAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "gunir/compiler/parser/big_query.ll"
{ return EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "gunir/compiler/parser/big_query.ll"
{ return NOT_EQUAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "gunir/compiler/parser/big_query.ll"
{ return NOT_EQUAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_AND; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_NOT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_OR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_XOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_LEFT_SHIFT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "gunir/compiler/parser/big_query.ll"
{ return BITWISE_RIGHT_SHIFT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_AND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_NOT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 64 "gunir/compiler/parser/big_query.ll"
{ return SLASH; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 65 "gunir/compiler/parser/big_query.ll"
{ return STAR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 66 "gunir/compiler/parser/big_query.ll"
{ return PLUS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "gunir/compiler/parser/big_query.ll"
{ return MINUS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "gunir/compiler/parser/big_query.ll"
{ return REMAINDER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "gunir/compiler/parser/big_query.ll"
{ return DOT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "gunir/compiler/parser/big_query.ll"
{ return COLON; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "gunir/compiler/parser/big_query.ll"
{ return COMMA; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "gunir/compiler/parser/big_query.ll"
{ return SEMICOLON; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "gunir/compiler/parser/big_query.ll"
{ return LPAREN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "gunir/compiler/parser/big_query.ll"
{ return RPAREN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "gunir/compiler/parser/big_query.ll"
{ return LSQUARE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "gunir/compiler/parser/big_query.ll"
{ return RSQUARE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "gunir/compiler/parser/big_query.ll"
{ return LCURLY; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "gunir/compiler/parser/big_query.ll"
{ return RCURLY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "gunir/compiler/parser/big_query.ll"
{ return HISTORY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "gunir/compiler/parser/big_query.ll"
{ return SHOW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "gunir/compiler/parser/big_query.ll"
{ return HELP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "gunir/compiler/parser/big_query.ll"
{ return QUIT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "gunir/compiler/parser/big_query.ll"
{ return QUIT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "gunir/compiler/parser/big_query.ll"
{ return DEFINE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "gunir/compiler/parser/big_query.ll"
{ return CREATE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "gunir/compiler/parser/big_query.ll"
{ return DROP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "gunir/compiler/parser/big_query.ll"
{ return SELECT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "gunir/compiler/parser/big_query.ll"
{ return WITHIN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "gunir/compiler/parser/big_query.ll"
{ return RECORD; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "gunir/compiler/parser/big_query.ll"
{ return AS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "gunir/compiler/parser/big_query.ll"
{ return FROM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "gunir/compiler/parser/big_query.ll"
{ return WHERE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "gunir/compiler/parser/big_query.ll"
{ return JOIN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "gunir/compiler/parser/big_query.ll"
{ return INNER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "gunir/compiler/parser/big_query.ll"
{ return LEFT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "gunir/compiler/parser/big_query.ll"
{ return OUTER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "gunir/compiler/parser/big_query.ll"
{ return ON; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "gunir/compiler/parser/big_query.ll"
{ return GROUPBY; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "gunir/compiler/parser/big_query.ll"
{ return HAVING; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "gunir/compiler/parser/big_query.ll"
{ return ORDERBY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "gunir/compiler/parser/big_query.ll"
{ return DISTINCT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "gunir/compiler/parser/big_query.ll"
{ return DESC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "gunir/compiler/parser/big_query.ll"
{ return ASC; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "gunir/compiler/parser/big_query.ll"
{ return LIMIT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_OR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_AND; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 109 "gunir/compiler/parser/big_query.ll"
{ return LOGICAL_NOT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "gunir/compiler/parser/big_query.ll"
{ return CONTAINS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 111 "gunir/compiler/parser/big_query.ll"
{ return DIV; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
#line 113 "gunir/compiler/parser/big_query.ll"
{ return ENDOF; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 115 "gunir/compiler/parser/big_query.ll"
{
    gunir_lval._bool = true;
    return BOOLEAN;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "gunir/compiler/parser/big_query.ll"
{
    gunir_lval._bool = false;
    return BOOLEAN;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "gunir/compiler/parser/big_query.ll"
{
    dc::StringMessage* m = NewMessage<dc::StringMessage>(memory_pool);
    *(m->mutable_char_string()) = std::string(yytext);
    gunir_lval._string = m;
    return ID;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "gunir/compiler/parser/big_query.ll"
{
    gunir_lval._int = atol(yytext);
    return INT;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "gunir/compiler/parser/big_query.ll"
{
    gunir_lval._float = atof(yytext);
    return FLOAT;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 142 "gunir/compiler/parser/big_query.ll"
{
    /* start match char string when first find quote:" */
    char_string_content.clear();
    quote_type = kDouble;
    BEGIN(STR);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "gunir/compiler/parser/big_query.ll"
{
    char_string_content.clear();
    quote_type = kSingle;
    BEGIN(STR);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 155 "gunir/compiler/parser/big_query.ll"
{
    if ((quote_type == kSingle && yytext[0] == '\"') ||
        (quote_type == kDouble && yytext[0] == '\'')) {
        char_string_content.push_back(yytext[0]); 
    } else {
        /* saw closing quote" - all done */
        /* return string constant token type and value to parser */

        BEGIN(INITIAL);
        dc::StringMessage* m = NewMessage<dc::StringMessage>(memory_pool);

        *(m->mutable_char_string()) = char_string_content;
        gunir_lval._string = m;
        return STRING;
    }
}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 172 "gunir/compiler/parser/big_query.ll"
{
    /* error - unterminated string constant */
    /* generate error message */

    print_message("lex parse error, unexpected \\n", output);
    return LEX_ERROR;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 180 "gunir/compiler/parser/big_query.ll"
{
    char_string_content.push_back(yytext[1]); 
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 184 "gunir/compiler/parser/big_query.ll"
{
    /* it is a escaped quote:' */
    char_string_content.push_back(yytext[1]); 
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 189 "gunir/compiler/parser/big_query.ll"
{
    /* it is a escaped quote:" */
    char_string_content.push_back(yytext[1]); 
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 194 "gunir/compiler/parser/big_query.ll"
{
    /* octal escape sequence */
    int result;
    sscanf(yytext + 1, "%o", &result );

    /* error, constant is out-of-bounds */
    if (result > 0xff) {
        print_message("lex parse error, constant is out-of-bounds", output);
        return LEX_ERROR;
    } else {
        char_string_content.push_back(static_cast<char>(result)); 
    }
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 208 "gunir/compiler/parser/big_query.ll"
{
    /* generate error - bad escape sequence; something
     * like '\48' or '\0777777'
     */

    print_message("lex parse error, constant is out-of-bounds", output);
    return LEX_ERROR;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 217 "gunir/compiler/parser/big_query.ll"
{
    char_string_content.push_back('\n'); 
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 221 "gunir/compiler/parser/big_query.ll"
{
    char_string_content.push_back('\t'); 
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 225 "gunir/compiler/parser/big_query.ll"
{
    char_string_content.push_back('\\'); 
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 229 "gunir/compiler/parser/big_query.ll"
{
    /* regex match all content in quote:" */
    char *yptr = yytext;

    while (*yptr) {
        char_string_content.push_back(*yptr); 
        yptr++;
    }
}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 239 "gunir/compiler/parser/big_query.ll"
{
    // return WS;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 243 "gunir/compiler/parser/big_query.ll"
{
    print_message("lex parse error", output);
    return LEX_ERROR;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 248 "gunir/compiler/parser/big_query.ll"
ECHO;
	YY_BREAK
#line 1597 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 *  gunir_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if (  gunir_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of  gunir_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					 gunir_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			 gunir_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *)  gunir_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 202 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 202 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 201);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					 gunir_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if (  gunir_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void  gunir_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
         gunir_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
             gunir__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	 gunir__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	 gunir__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void  gunir__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		 gunir_pop_buffer_state();
	 *		 gunir_push_buffer_state(new_buffer);
     */
	 gunir_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	 gunir__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF ( gunir_wrap()) processing, but the only time this flag
	 * is looked at is after  gunir_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void  gunir__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE  gunir__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE)  gunir_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in  gunir__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *)  gunir_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in  gunir__create_buffer()" );

	b->yy_is_our_buffer = 1;

	 gunir__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with  gunir__create_buffer()
 * @param yyscanner The scanner object.
 */
    void  gunir__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		 gunir_free((void *) b->yy_ch_buf ,yyscanner );

	 gunir_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a  gunir_restart() or at EOF.
 */
    static void  gunir__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	 gunir__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then  gunir__init_buffer was _probably_
     * called from  gunir_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void  gunir__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		 gunir__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void  gunir_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	 gunir_ensure_buffer_stack(yyscanner);

	/* This block is copied from  gunir__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from  gunir__switch_to_buffer. */
	 gunir__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void  gunir_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	 gunir__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		 gunir__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void  gunir_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**) gunir_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in  gunir_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**) gunir_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in  gunir_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE  gunir__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE)  gunir_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in  gunir__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	 gunir__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to  gunir_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *        gunir__scan_bytes() instead.
 */
YY_BUFFER_STATE  gunir__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return  gunir__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to  gunir_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE  gunir__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *)  gunir_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in  gunir__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b =  gunir__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in  gunir__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE  gunir_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int  gunir_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int  gunir_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE * gunir_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE * gunir_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int  gunir_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char * gunir_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void  gunir_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void  gunir_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( " gunir_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void  gunir_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( " gunir_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see  gunir__switch_to_buffer
 */
void  gunir_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void  gunir_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int  gunir_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void  gunir_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/*  gunir_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int  gunir_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t)  gunir_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/*  gunir_lex_init_extra has the same functionality as  gunir_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to  gunir_alloc in
 * the yyextra field.
 */

int  gunir_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

     gunir_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t)  gunir_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
     gunir_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from  gunir_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     *  gunir_lex_init()
     */
    return 0;
}

/*  gunir_lex_destroy is for both reentrant and non-reentrant scanners. */
int  gunir_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		 gunir__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		 gunir_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	 gunir_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
         gunir_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     *  gunir_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
     gunir_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void * gunir_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void * gunir_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void  gunir_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see  gunir_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 248 "gunir/compiler/parser/big_query.ll"



void print_message(const char* msg, std::ostream* output) {
    *output << msg << std::endl;
}

