cc_binary(
    name = 'create_table',
    srcs = 'create_table.cc',
    deps = [
        '//gunir/utils:create_table_tool',
        '//gunir/utils:message_utils',
        '//thirdparty/gflags:gflags',
        '//thirdparty/glog:glog',
        '//toft/base:binary_version'
    ]
)

cc_binary(
    name = 'parse_log_main',
    srcs = 'parse_log_main.cc',
    deps = [
        '//gunir/utils:parse_log_tool',
        '//thirdparty/gflags:gflags',
        '//thirdparty/glog:glog',
    ]
)
